// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxiesnrgfjjdcosctzkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4aWVzbnJnZmpqZGNvc2N0emtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTQzNzUsImV4cCI6MjA3MTI5MDM3NX0.rdJ-VwzNyIGfIE0imN0WTCYXvAugy5XeM44-KR8QFT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});